name: List Team Members

on: [push]

permissions:
  contents: read
  

jobs:
  list-team-members:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: List team members
        id: get-members
        uses: garnertb/get-team-members@v1
        with:
          org: uncoma-curza-lab
          team_slug: peylw24
          token: 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

      - run: "echo ${{ steps.get-members.outputs.members }}"
        shell: bash


          
        
