name: Generate Member Pages
on:
  push:
    branches: [crea_alumnos]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get team members
        id: get_members
        run: |
            bearer_token="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"
            
            organization="uncoma-curza-lab"
            team="peylw24"

            # Function to fetch and process team members
            fetch_team_members() {
            page=1
            while true; do
                url="https://api.github.com/orgs/$organization/teams/$team/members?page=$page"

                response=$(curl -s -H "Authorization: Bearer $bearer_token" "$url")

                # Check for errors
                if jq -e '.message' <<< "$response" > /dev/null; then
                error_message=$(jq -r .message <<< "$response")
                echo "Error: $error_message"
                exit 1
                fi

                # Extract member logins
                jq -r '.[].login' <<< "$response" >> members.txt

                # Check for next page
                next_page=$(jq -r '.["links"][] | select(.rel == "next")["href"]' <<< "$response")

                # Break loop if no next page
                if [[ -z "$next_page" ]]; then
                break
                fi

                page=$((page+1))
            done
            }

            # Call the function to fetch and process members
            fetch_team_members

            # Count and print the number of members
            num_members=$(wc -l members.txt | awk '{print $1}')
            echo "Number of members: $num_members"

            # Print the list of members
            cat members.txt

      - name: Generate member pages
        run: |
          while IFS= read -r member; do
            # Adapt the name extraction according to your structure
            alumno=$(echo "$member" | sed 's/niunmango/Ramiro García Poggi/g')
            # Check if the subdirectory already exists
            if [ ! -d "alumnos/$alumno" ]; then
              mkdir -p "alumnos/$alumno"
              cp index.html "alumnos/$alumno/index.html"
              sed -i "s/niunmango/$alumno/g" "alumnos/$alumno/index.html"
              echo "<li><a href=\"alumnos/$alumno/index.html\">$alumno</a></li>" >> index.html
            fi
          done < members.txt

      - name: Generate member pages (main index.html)
        run: |
            # Clear existing links from main index.html
            sed -i '/<li><a href="\/alumnos\/.*\/index\.html">.*<\/a><\/li>/d' index.html

            # Loop through members and add links to main index.html
            while IFS= read -r member; do
                echo "<li><a href=\"alumnos/$member/index.html\">$member</a></li>" >> index.html
            done < members.txt

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .


          
        