name: Generate Member Pages

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get team members
        id: get_members
        run: |
          curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/orgs/your-org/teams/your-team/members | jq -r '.[] | .login' > members.txt
      - name: Generate member pages
        run: |
          while IFS= read -r member; do
            # ... (your existing code for generating member pages)
          done < members.txt
      - name: Update index.html
        run: |
          # Clear the existing list of links
          sed -i '/<li><a href="\/alumnos\/.*\/index\.html">.*<\/a><\/li>/d' index.html
          # Append new links
          while IFS= read -r member; do
            echo "<li><a href=\"alumnos/$member/index.html\">$member</a></li>" >> index.html
          done < members.txt
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
